import { Chivo } from "next/font/google";
import "./globals.css";

const chivo = Chivo({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${chivo.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
